production:
  adapter: mysql
  encoding: utf8
  database: demanda_production
  pool: 5
  username: root
  password: s3inf0 
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql
  encoding: utf8
  database: demanda_development
  pool: 5
  username: root
  password: s3inf0
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: demanda_test
  pool: 5
  username: root
  password: s3inf0
  socket: /var/run/mysqld/mysqld.sock

